### ISSUE TITLE
Search and Filter V3 Beta: Critical Error on Archive Page with query

### ISSUE THREAD

**Issue by beckej13820** [rmorse/search-filter#76]
I'm testing Search and Filter v3 Beta on a WordPress site / portfolio site.

I'm using the FSE Theme Riverbank. I have been using Search & Filter as a way to drill into my posts. Here's what I'm trying to do (screenshot showing Search and Filter legacy)

![Screenshot 2024-03-04 at 11 57 14 AM](https://github.com/rmorse/search-filter/assets/29982981/f764b565-386e-435f-beb5-4d450c9a3345)

Very excited for the new interface and the deeper integration with Gutenberg. Interface was very nice, and it was very easy to set up. I set up my index template to use the new beta plugin:

![Screenshot 2024-03-04 at 12 01 56 PM](https://github.com/rmorse/search-filter/assets/29982981/065c7ce0-e7bf-4294-b7bb-0611c6c7afad)

Unfortunately, something is causing a fatal error on the website. I've included the stack trace (I hope it helps!):

  thrown in /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field.php on line 631
[04-Mar-2024 16:38:34 UTC] PHP Fatal error:  Uncaught Search_Filter\Core\Exception: The input or control type has not been set. in /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field-factory.php:168
Stack trace:
#0 /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field-factory.php(146): Search_Filter\Fields\Field_Factory::get_field_atts(Array)
#1 /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field-factory.php(213): Search_Filter\Fields\Field_Factory::get_field_class(Array)
#2 /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/class-rest-api.php(117): Search_Filter\Fields\Field_Factory::create(Array)
#3 /home/edbecksu/ed-beck.com/wp-includes/rest-api/class-wp-rest-server.php(1193): Search_Filter\Rest_API->create_field(Object(WP_REST_Request))
#4 /home/edbecksu/ed-beck.com/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/search-filter/...', Array, NULL)
#5 /home/edbecksu/ed-beck.com/wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch(Object(WP_REST_Request))
#6 /home/edbecksu/ed-beck.com/wp-includes/rest-api.php(424): WP_REST_Server->serve_request('/search-filter/...')
#7 /home/edbecksu/ed-beck.com/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#8 /home/edbecksu/ed-beck.com/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#9 /home/edbecksu/ed-beck.com/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#10 /home/edbecksu/ed-beck.com/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#11 /home/edbecksu/ed-beck.com/wp-includes/class-wp.php(813): WP->parse_request('')
#12 /home/edbecksu/ed-beck.com/wp-includes/functions.php(1336): WP->main('')
#13 /home/edbecksu/ed-beck.com/wp-blog-header.php(16): wp()
#14 /home/edbecksu/ed-beck.com/index.php(17): require('/home/edbecksu/...')
#15 {main}
  thrown in /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field-factory.php on line 168
[04-Mar-2024 16:39:22 UTC] PHP Warning:  Undefined array key "section" in /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/rest-api/class-queries.php on line 295
[04-Mar-2024 16:39:37 UTC] PHP Fatal error:  Uncaught TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, function "Search_Filter\Fields\Filter\esc_pass_through" not found or invalid function name in /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field.php:631
Stack trace:
#0 /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field.php(631): call_user_func('Search_Filter\\F...', Array)
#1 /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field.php(592): Search_Filter\Fields\Field->escape_render_data(Array, Array)
#2 /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field.php(490): Search_Filter\Fields\Field->build()
#3 /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/integrations/class-gutenberg.php(275): Search_Filter\Fields\Field->render()
#4 /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/integrations/class-gutenberg.php(299): Search_Filter\Integrations\Gutenberg::render_field(Array)
#5 /home/edbecksu/ed-beck.com/wp-includes/class-wp-block.php(258): Search_Filter\Integrations\Gutenberg::render_filter_field(Array, '', Object(WP_Block))
#6 /home/edbecksu/ed-beck.com/wp-includes/class-wp-block.php(244): WP_Block->render()
#7 /home/edbecksu/ed-beck.com/wp-includes/class-wp-block.php(244): WP_Block->render()
#8 /home/edbecksu/ed-beck.com/wp-includes/blocks.php(1484): WP_Block->render()
#9 /home/edbecksu/ed-beck.com/wp-includes/blocks.php(1522): render_block(Array)
#10 /home/edbecksu/ed-beck.com/wp-content/plugins/gutenberg/build/block-library/blocks/template-part.php(150): do_blocks('<!-- wp:columns...')
#11 /home/edbecksu/ed-beck.com/wp-includes/class-wp-block.php(258): gutenberg_render_block_core_template_part(Array, '', Object(WP_Block))
#12 /home/edbecksu/ed-beck.com/wp-includes/class-wp-block.php(244): WP_Block->render()
#13 /home/edbecksu/ed-beck.com/wp-includes/blocks.php(1484): WP_Block->render()
#14 /home/edbecksu/ed-beck.com/wp-includes/blocks.php(1522): render_block(Array)
#15 /home/edbecksu/ed-beck.com/wp-includes/block-template.php(263): do_blocks('<!-- wp:templat...')
#16 /home/edbecksu/ed-beck.com/wp-includes/template-canvas.php(12): get_the_block_template_html()
#17 /home/edbecksu/ed-beck.com/wp-includes/template-loader.php(106): include('/home/edbecksu/...')
#18 /home/edbecksu/ed-beck.com/wp-blog-header.php(19): require_once('/home/edbecksu/...')
#19 /home/edbecksu/ed-beck.com/index.php(17): require('/home/edbecksu/...')
#20 {main}
  thrown in /home/edbecksu/ed-beck.com/wp-content/plugins/search-filter/includes/fields/class-field.php on line 631

**Comment by beckej13820** [comment]
In the stack trace it says- The input and control type is not set.

When I look at the interface, I have set the Search bar to Text, the Categories to Checkbox, Control Field 1 to Submit, Control Field 2 to Reset.

Please let me know if you would like me to try anything for troubleshooting.

Also, I just filled out the form to get emails, if this is something I should put in Slack, I'm just waiting for an invite. Thanks!

**Comment by rmorse** [comment]
Hey @beckej13820  - thanks for taking the time to log this.

We've just released an update (beta.11) and it should be fully FSE compatible! Can you let me know if it works for you?

RE the slack channel, if you press the link in the header (of our admin page), does that not get you into the channel? It should be open 🫰

**Comment by beckej13820** [comment]
@rmorse I am getting the beta version of the plugin from https://searchandfilter.com/version-3/

The version available on that page is still beta.10.

Where should I download beta.11?

**Comment by rmorse** [comment]
After you've installed it, the update should appear in your admin dashboard
(after a short while).

Are you seeing that?

I'll get the link updated with the latest version tomorrow, thanks for
flagging that!

**Comment by rmorse** [comment]
@beckej13820 did you manage to update ok?
